name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Debug SSH environment variables
      run: |
        echo "SERVER_IP: $SERVER_IP"
        echo "SERVER_USER: $SERVER_USER"

    - name: Deploy to server using screen and nohup
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        
        # SSH into the server and run FastAPI inside a screen session
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
            cd /root/SVGAPI &&
            git pull origin main &&
            source .venv/bin/activate &&
            pip install -r requirements.txt
        EOF
